version: "3.9"
services:
    api:
        build: .
        restart: always
        ports:
            - "9090:9090"
            - "7000:7000"
        depends_on:
            kafka:
                condition: service_healthy
        
        environment:
            DATABASE_URL: "root:@tcp(mysql:3306)/test"
            KAFKA_PRODUCER_BOOTSTRAP_SERVERS: "kafka:9092"
    
    mysql:
        image: mysql:5.7
        volumes:
            - "db_data:/var/lib/mysql"
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ""
            MYSQL_DATABASE: test
            MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    
    zookeeper:
        image: docker.io/bitnami/zookeeper:3.7
        ports:
            - "2181:2181"
        volumes:
            - "zookeeper_data:/bitnami"
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes
    kafka:
        image: docker.io/bitnami/kafka:2
        ports:
            - "9092:9092"
        volumes:
            - "kafka_data:/bitnami"
        environment:
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
            - ALLOW_PLAINTEXT_LISTENER=yes
            - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
        depends_on:
            - zookeeper
        healthcheck:
            test: [ "CMD", "kafka-topics.sh", "--list", "--zookeeper", "zookeeper:2181" ]
            interval: 40s
            timeout: 5s
            retries: 30
        

volumes:
    zookeeper_data:
        driver: local
    kafka_data:
        driver: local
    db_data:
        driver: local
